/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini_dbms_proyectoestru2_q2_2026;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author bamay
 */
public class Interfaz extends javax.swing.JFrame {
    
    private ArrayList<Campos> lista_Campos; // Una lista que se va guardar todos los campos que se vayan a estar creando - temporalmente
    //private ArrayList<Registro> lista_Registros; // lista temporal que guarda todos los archivs
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        lista_Campos = new ArrayList<>(); // lista de campos inicializada y vacia
        
        // cambiandole los items de opciones de la combobox
        JComboBox_TipoDeDatoCampo.removeAllItems();
        JComboBox_TipoDeDatoCampo.addItem("int"); // 0 = int
        JComboBox_TipoDeDatoCampo.addItem("float"); // 1 = float
        JComboBox_TipoDeDatoCampo.addItem("boolean"); // 2 = bool
        JComboBox_TipoDeDatoCampo.addItem("char"); // 3 = char
        JComboBox_TipoDeDatoCampo.addItem("string"); // 4 =string
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDialog_CrearCampos = new javax.swing.JDialog();
        JPanel_CrearCampos = new javax.swing.JPanel();
        JLabel_CrearCampos = new javax.swing.JLabel();
        JLabel_NombreCampos = new javax.swing.JLabel();
        JTextField_NombreDelCampo = new javax.swing.JTextField();
        JLabel_TipoDeCampo = new javax.swing.JLabel();
        JLabel_LlavePrimSecun = new javax.swing.JLabel();
        JLabel_TamanioCampo = new javax.swing.JLabel();
        JTextField_TamanioCampo = new javax.swing.JTextField();
        JButton_CrearCampos = new javax.swing.JButton();
        JButton_SalirCrearCampos = new javax.swing.JButton();
        JRadioButton_LlavePrimaria = new javax.swing.JRadioButton();
        JRadioButton_LlaveSecundaria = new javax.swing.JRadioButton();
        JComboBox_TipoDeDatoCampo = new javax.swing.JComboBox<>();
        JDialog_ListarCampos = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        JLabel_CrearCampos1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_ListaDeCampos = new javax.swing.JTable();
        JButton_ModificarCampos = new javax.swing.JButton();
        JButton_BorrarCampos = new javax.swing.JButton();
        JButton_SalirListaCampos = new javax.swing.JButton();
        JPanel_JFrame = new javax.swing.JPanel();
        JMenuBar_1 = new javax.swing.JMenuBar();
        JMenu_Archivo = new javax.swing.JMenu();
        JMenuItem_CrearArchivo = new javax.swing.JMenuItem();
        JMenuItem_AbrirArchivo = new javax.swing.JMenuItem();
        JMenuItem_GuardarCambios = new javax.swing.JMenuItem();
        JMenuItem_CerrarArchivo = new javax.swing.JMenuItem();
        JMenuItem_SalirProg = new javax.swing.JMenuItem();
        JMenu_Campos = new javax.swing.JMenu();
        JMenuItem_CrearCampos = new javax.swing.JMenuItem();
        JMenuItem_ListarCampos = new javax.swing.JMenuItem();
        JMenuItem_ModificarCampos = new javax.swing.JMenuItem();
        JMenuItem_BorrarCampos = new javax.swing.JMenuItem();
        JMenu_Registros = new javax.swing.JMenu();
        JMenuItem_IntroducirRegistros = new javax.swing.JMenuItem();
        JMenuItem_ModificarRegistros = new javax.swing.JMenuItem();
        JMenuItem_BuscarRegistros = new javax.swing.JMenuItem();
        JMenuItem_BorrarRegistros = new javax.swing.JMenuItem();
        JMenuItem_ListarRegistros = new javax.swing.JMenuItem();
        JMenuItem_CargarRegistrosPrueba = new javax.swing.JMenuItem();
        JMenuItem_CruzarArchivos = new javax.swing.JMenuItem();

        JLabel_CrearCampos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JLabel_CrearCampos.setText("Crear Campos");

        JLabel_NombreCampos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLabel_NombreCampos.setText("Nombre del campo:");

        JLabel_TipoDeCampo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLabel_TipoDeCampo.setText("Tipo de dato del campo:");

        JLabel_LlavePrimSecun.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLabel_LlavePrimSecun.setText("Llave primaria/Llave secundaria:");
        JLabel_LlavePrimSecun.setToolTipText("En caso no aplique a ninguna de las dos, no seleccionar");

        JLabel_TamanioCampo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLabel_TamanioCampo.setText("Tamaño del campo:");

        JButton_CrearCampos.setText("Crear campo");
        JButton_CrearCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_CrearCamposMouseClicked(evt);
            }
        });

        JButton_SalirCrearCampos.setBackground(new java.awt.Color(204, 0, 0));
        JButton_SalirCrearCampos.setText("Salir");
        JButton_SalirCrearCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_SalirCrearCamposMouseClicked(evt);
            }
        });

        JRadioButton_LlavePrimaria.setText("Llave primaria");
        JRadioButton_LlavePrimaria.setToolTipText("");

        JRadioButton_LlaveSecundaria.setText("Llave secundaria");
        JRadioButton_LlaveSecundaria.addActionListener(this::JRadioButton_LlaveSecundariaActionPerformed);

        JComboBox_TipoDeDatoCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout JPanel_CrearCamposLayout = new javax.swing.GroupLayout(JPanel_CrearCampos);
        JPanel_CrearCampos.setLayout(JPanel_CrearCamposLayout);
        JPanel_CrearCamposLayout.setHorizontalGroup(
            JPanel_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_CrearCamposLayout.createSequentialGroup()
                .addGroup(JPanel_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanel_CrearCamposLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JLabel_TamanioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextField_TamanioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanel_CrearCamposLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(JLabel_CrearCampos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanel_CrearCamposLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(JPanel_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanel_CrearCamposLayout.createSequentialGroup()
                                .addComponent(JLabel_TipoDeCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JComboBox_TipoDeDatoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanel_CrearCamposLayout.createSequentialGroup()
                                .addGroup(JPanel_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLabel_LlavePrimSecun)
                                    .addGroup(JPanel_CrearCamposLayout.createSequentialGroup()
                                        .addComponent(JLabel_NombreCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JTextField_NombreDelCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JPanel_CrearCamposLayout.createSequentialGroup()
                                        .addComponent(JRadioButton_LlavePrimaria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(142, 142, 142)
                                        .addComponent(JRadioButton_LlaveSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 1, Short.MAX_VALUE)))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_CrearCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JButton_SalirCrearCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JButton_CrearCampos)
                .addContainerGap())
        );
        JPanel_CrearCamposLayout.setVerticalGroup(
            JPanel_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_CrearCamposLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(JLabel_CrearCampos)
                .addGap(37, 37, 37)
                .addGroup(JPanel_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_NombreCampos)
                    .addComponent(JTextField_NombreDelCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(JPanel_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel_TipoDeCampo)
                    .addComponent(JComboBox_TipoDeDatoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanel_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLabel_TamanioCampo)
                    .addComponent(JTextField_TamanioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JLabel_LlavePrimSecun, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPanel_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRadioButton_LlavePrimaria)
                    .addComponent(JRadioButton_LlaveSecundaria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(JPanel_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton_CrearCampos)
                    .addComponent(JButton_SalirCrearCampos))
                .addContainerGap())
        );

        javax.swing.GroupLayout JDialog_CrearCamposLayout = new javax.swing.GroupLayout(JDialog_CrearCampos.getContentPane());
        JDialog_CrearCampos.getContentPane().setLayout(JDialog_CrearCamposLayout);
        JDialog_CrearCamposLayout.setHorizontalGroup(
            JDialog_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_CrearCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JDialog_CrearCamposLayout.setVerticalGroup(
            JDialog_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_CrearCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JLabel_CrearCampos1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JLabel_CrearCampos1.setText("Lista de Campos");

        JTable_ListaDeCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTable_ListaDeCampos);

        JButton_ModificarCampos.setText("Modificar Campo");

        JButton_BorrarCampos.setText("Borrar Campos");

        JButton_SalirListaCampos.setBackground(new java.awt.Color(204, 0, 0));
        JButton_SalirListaCampos.setText("Salir");
        JButton_SalirListaCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_SalirListaCamposMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(JLabel_CrearCampos1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JButton_ModificarCampos)
                                .addGap(18, 18, 18)
                                .addComponent(JButton_BorrarCampos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JButton_SalirListaCampos))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(JLabel_CrearCampos1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton_ModificarCampos)
                    .addComponent(JButton_BorrarCampos)
                    .addComponent(JButton_SalirListaCampos))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JDialog_ListarCamposLayout = new javax.swing.GroupLayout(JDialog_ListarCampos.getContentPane());
        JDialog_ListarCampos.getContentPane().setLayout(JDialog_ListarCamposLayout);
        JDialog_ListarCamposLayout.setHorizontalGroup(
            JDialog_ListarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JDialog_ListarCamposLayout.setVerticalGroup(
            JDialog_ListarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JPanel_JFrameLayout = new javax.swing.GroupLayout(JPanel_JFrame);
        JPanel_JFrame.setLayout(JPanel_JFrameLayout);
        JPanel_JFrameLayout.setHorizontalGroup(
            JPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );
        JPanel_JFrameLayout.setVerticalGroup(
            JPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        JMenu_Archivo.setText("Archivos");
        JMenu_Archivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenu_ArchivoMouseClicked(evt);
            }
        });
        JMenu_Archivo.addActionListener(this::JMenu_ArchivoActionPerformed);

        JMenuItem_CrearArchivo.setText("Crear archivo");
        JMenuItem_CrearArchivo.addActionListener(this::JMenuItem_CrearArchivoActionPerformed);
        JMenu_Archivo.add(JMenuItem_CrearArchivo);

        JMenuItem_AbrirArchivo.setText("Abrir archivo");
        JMenuItem_AbrirArchivo.addActionListener(this::JMenuItem_AbrirArchivoActionPerformed);
        JMenu_Archivo.add(JMenuItem_AbrirArchivo);

        JMenuItem_GuardarCambios.setText("Guardar cambios");
        JMenu_Archivo.add(JMenuItem_GuardarCambios);

        JMenuItem_CerrarArchivo.setText("Cerrar archivo");
        JMenu_Archivo.add(JMenuItem_CerrarArchivo);

        JMenuItem_SalirProg.setText("Salir");
        JMenu_Archivo.add(JMenuItem_SalirProg);

        JMenuBar_1.add(JMenu_Archivo);

        JMenu_Campos.setText("Campos");

        JMenuItem_CrearCampos.setText("Crear campos");
        JMenuItem_CrearCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenuItem_CrearCamposMouseClicked(evt);
            }
        });
        JMenuItem_CrearCampos.addActionListener(this::JMenuItem_CrearCamposActionPerformed);
        JMenu_Campos.add(JMenuItem_CrearCampos);

        JMenuItem_ListarCampos.setText("Listar campos");
        JMenu_Campos.add(JMenuItem_ListarCampos);

        JMenuItem_ModificarCampos.setText("Modificar campos");
        JMenu_Campos.add(JMenuItem_ModificarCampos);

        JMenuItem_BorrarCampos.setText("Borrar campos");
        JMenu_Campos.add(JMenuItem_BorrarCampos);

        JMenuBar_1.add(JMenu_Campos);

        JMenu_Registros.setText("Registros");

        JMenuItem_IntroducirRegistros.setText("Introducir registros");
        JMenu_Registros.add(JMenuItem_IntroducirRegistros);

        JMenuItem_ModificarRegistros.setText("Modificar registros");
        JMenu_Registros.add(JMenuItem_ModificarRegistros);

        JMenuItem_BuscarRegistros.setText("Buscar registros");
        JMenu_Registros.add(JMenuItem_BuscarRegistros);

        JMenuItem_BorrarRegistros.setText("Borrar registros");
        JMenu_Registros.add(JMenuItem_BorrarRegistros);

        JMenuItem_ListarRegistros.setText("Listar registros");
        JMenu_Registros.add(JMenuItem_ListarRegistros);

        JMenuItem_CargarRegistrosPrueba.setText("Cargar registros ");
        JMenu_Registros.add(JMenuItem_CargarRegistrosPrueba);

        JMenuItem_CruzarArchivos.setText("Cruzar archivos");
        JMenu_Registros.add(JMenuItem_CruzarArchivos);

        JMenuBar_1.add(JMenu_Registros);

        setJMenuBar(JMenuBar_1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_JFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_JFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenu_ArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenu_ArchivoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenu_ArchivoMouseClicked

    private void JMenuItem_CrearArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_CrearArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar archivo como...");
        
        // Para que solo se muestre archivos .txt y tambien los archivos creados sean .txt
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de texto (*.txt)", "txt");
        fileChooser.setFileFilter(filtro);
        int seleccion = fileChooser.showSaveDialog(this);
        
        // solo para verificar que el usuario presiono guardar 
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo_Seleccionado = fileChooser.getSelectedFile(); 
            String ruta = archivo_Seleccionado.getAbsolutePath();
            // verificar si termina en .txt
            if (!ruta.toLowerCase().endsWith(".txt")) {
                ruta+= ".txt";
            }
            File archivoFinal = new File(ruta);
            
            if (archivoFinal.exists()) { // si el archivo existe/ya existe
                JOptionPane.showMessageDialog(this, "El archivo ya existe");
                return;
            }
            
            // crear el archivo
            try {
                try (RandomAccessFile archivo = new RandomAccessFile(archivoFinal, "rw")) {
                    archivo.setLength(0); // archivo vacio (esta con 0 bytes)
                }
                JOptionPane.showMessageDialog(this, "El archivo se creo");
            } catch (IOException e) { // en caso si hubo algun error
                JOptionPane.showMessageDialog(this, "Hubo un error al crear archivo: " + e.getMessage());
            }
        } else { // en caso se decidio seleccionar "cancelar"
            JOptionPane.showMessageDialog(this, "No se selecciono ningun archivo");
        }
    }//GEN-LAST:event_JMenuItem_CrearArchivoActionPerformed

    private void JMenuItem_AbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_AbrirArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de texto (*.txt)", "txt");
        fileChooser.setFileFilter(filter);
        int estado = fileChooser.showOpenDialog(this);
        
        if (estado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            
        }
    }//GEN-LAST:event_JMenuItem_AbrirArchivoActionPerformed

        
    // No funciono con Mouse Click - JDialogs
    private void JMenuItem_CrearCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenuItem_CrearCamposMouseClicked
        // vacio
    }//GEN-LAST:event_JMenuItem_CrearCamposMouseClicked

    // Abre el JDialog_CrearCampos y cerrando el JFrame
    private void JMenuItem_CrearCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_CrearCamposActionPerformed
        this.setVisible(false);
        expandir(JDialog_CrearCampos);
    }//GEN-LAST:event_JMenuItem_CrearCamposActionPerformed

    // Crear los campos una vez ya haya ingresado los datos requeridos
    private void JButton_CrearCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_CrearCamposMouseClicked
        Campos temporal = new Campos();
        
        // Verificar que los campos no esten vacios
        // 1. Verificando que el TextField del campo no este vacio 
        if (JTextField_NombreDelCampo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(JDialog_CrearCampos, "Ingrese el campo requerido (Nombre del campo)");
            return;
        }
        
        // 2. Guardar el nombre del campo en temporal con setNombre
        temporal.setNombre(JTextField_NombreDelCampo.getText());
        
        // 3. Verificar el ComboBox de que tipo de dato va ser el campo
        // Como es int private int tipoDato; entonces => 0 = int, 1 = float, 2 = bool, 3 = char, 4 = string
        int tipo_Seleccionado = JComboBox_TipoDeDatoCampo.getSelectedIndex(); // indice del seleccionado
        switch (tipo_Seleccionado){
            case 0 : // int
                temporal.setTipoDato(0);
                temporal.setTamanio("4");
                JTextField_TamanioCampo.setText("4");
                JTextField_TamanioCampo.setEnabled(false); // para que no pueda cambiar el "4" 
                break;
            case 1: // float
                temporal.setTipoDato(1);
                temporal.setTamanio("8");
                JTextField_TamanioCampo.setText("8");
                JTextField_TamanioCampo.setEnabled(false); // mismo pero "8"
                break;
            case 2: // bool
                temporal.setTipoDato(2);
                temporal.setTamanio("1"); // true/false solo ocupa 1 byte de espacio
                JTextField_TamanioCampo.setText("1");
                JTextField_TamanioCampo.setEnabled(false);
                break;
            case 3: // char
                if (JTextField_TamanioCampo.getText().isEmpty()) { // verificar que el tamanio no este vacio
                    JOptionPane.showMessageDialog(JDialog_CrearCampos, "Ingrese el campo requerido (tamanio del char)");
                    return;
                }
                temporal.setTipoDato(3);
                temporal.setTamanio(JTextField_TamanioCampo.getText());
                JTextField_TamanioCampo.setEnabled(true);
                break;
            case 4: // string
                if (JTextField_TamanioCampo.getText().isEmpty()) { // verificar que el tamanio no este vacio
                    JOptionPane.showMessageDialog(JDialog_CrearCampos, "Ingrese el campo requerido (tamanio del string)");
                    return;
                }
                temporal.setTipoDato(4);
                temporal.setTamanio(JTextField_TamanioCampo.getText());
                JTextField_TamanioCampo.setEnabled(true);
                break;
        }
        
        // 4. Llaves primarias y secundarias asignadas - validando que solo pueda escoger 1 pero no ambos y si no se escoge ambos dejando como campo normal
        if (JRadioButton_LlavePrimaria.isSelected()) {
            temporal.setLlavePrimaria(true);
            temporal.setLlaveSecundaria(false);
        } else if (JRadioButton_LlaveSecundaria.isSelected()) {
            temporal.setLlavePrimaria(false);
            temporal.setLlaveSecundaria(true);
        } else { // --> campo normal
            temporal.setLlavePrimaria(false);
            temporal.setLlaveSecundaria(false);
        }
        
        // 5. Agregarla a la lista_campos - temporal
        lista_Campos.add(temporal); // ya agregando el Campo temporal con todos lo requerido (nombre, tipodato, tamanio, llaveprimaria, llavesecundaria)
        
        // 6. mensaje que muestra que se realizo la creacion de campo
        JOptionPane.showMessageDialog(JDialog_CrearCampos, "Campo '" + temporal.getNombre() + "' ha creado");
        
        // 7. limpiar los componentes
        JTextField_NombreDelCampo.setText("");
        JTextField_TamanioCampo.setText("");
        
    }//GEN-LAST:event_JButton_CrearCamposMouseClicked

    private void JRadioButton_LlaveSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioButton_LlaveSecundariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRadioButton_LlaveSecundariaActionPerformed

    // Cerrar el JDialog de crear campos y mostrar el JFrame
    private void JButton_SalirCrearCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_SalirCrearCamposMouseClicked
        this.setVisible(true);
        JDialog_CrearCampos.dispose();
    }//GEN-LAST:event_JButton_SalirCrearCamposMouseClicked

    // Cerrar el JDialog de Listar campos y mostrar el JFrame
    private void JButton_SalirListaCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_SalirListaCamposMouseClicked
        this.setVisible(true);
        JDialog_ListarCampos.dispose();
    }//GEN-LAST:event_JButton_SalirListaCamposMouseClicked

    // Salir del JFrame (salir del programa en corto
    private void JMenu_ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenu_ArchivoActionPerformed
        
    }//GEN-LAST:event_JMenu_ArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }
    
    // para las JDialogs
    public void expandir(JDialog ventana) {
        ventana.pack();
        ventana.setModal(true);
        ventana.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_BorrarCampos;
    private javax.swing.JButton JButton_CrearCampos;
    private javax.swing.JButton JButton_ModificarCampos;
    private javax.swing.JButton JButton_SalirCrearCampos;
    private javax.swing.JButton JButton_SalirListaCampos;
    private javax.swing.JComboBox<String> JComboBox_TipoDeDatoCampo;
    private javax.swing.JDialog JDialog_CrearCampos;
    private javax.swing.JDialog JDialog_ListarCampos;
    private javax.swing.JLabel JLabel_CrearCampos;
    private javax.swing.JLabel JLabel_CrearCampos1;
    private javax.swing.JLabel JLabel_LlavePrimSecun;
    private javax.swing.JLabel JLabel_NombreCampos;
    private javax.swing.JLabel JLabel_TamanioCampo;
    private javax.swing.JLabel JLabel_TipoDeCampo;
    private javax.swing.JMenuBar JMenuBar_1;
    private javax.swing.JMenuItem JMenuItem_AbrirArchivo;
    private javax.swing.JMenuItem JMenuItem_BorrarCampos;
    private javax.swing.JMenuItem JMenuItem_BorrarRegistros;
    private javax.swing.JMenuItem JMenuItem_BuscarRegistros;
    private javax.swing.JMenuItem JMenuItem_CargarRegistrosPrueba;
    private javax.swing.JMenuItem JMenuItem_CerrarArchivo;
    private javax.swing.JMenuItem JMenuItem_CrearArchivo;
    private javax.swing.JMenuItem JMenuItem_CrearCampos;
    private javax.swing.JMenuItem JMenuItem_CruzarArchivos;
    private javax.swing.JMenuItem JMenuItem_GuardarCambios;
    private javax.swing.JMenuItem JMenuItem_IntroducirRegistros;
    private javax.swing.JMenuItem JMenuItem_ListarCampos;
    private javax.swing.JMenuItem JMenuItem_ListarRegistros;
    private javax.swing.JMenuItem JMenuItem_ModificarCampos;
    private javax.swing.JMenuItem JMenuItem_ModificarRegistros;
    private javax.swing.JMenuItem JMenuItem_SalirProg;
    private javax.swing.JMenu JMenu_Archivo;
    private javax.swing.JMenu JMenu_Campos;
    private javax.swing.JMenu JMenu_Registros;
    private javax.swing.JPanel JPanel_CrearCampos;
    private javax.swing.JPanel JPanel_JFrame;
    private javax.swing.JRadioButton JRadioButton_LlavePrimaria;
    private javax.swing.JRadioButton JRadioButton_LlaveSecundaria;
    private javax.swing.JTable JTable_ListaDeCampos;
    private javax.swing.JTextField JTextField_NombreDelCampo;
    private javax.swing.JTextField JTextField_TamanioCampo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
