/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini_dbms_proyectoestru2_q2_2026;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author bamay
 */
public class Interfaz extends javax.swing.JFrame {
    
    private ArrayList<Campos> lista_Campos; // Una lista que se va guardar todos los campos que se vayan a estar creando - temporalmente
    //private ArrayList<Registro> lista_Registros; // lista temporal que guarda todos los archivs -- despues de terminar campos continuar registro
    private File archivoActual;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        lista_Campos = new ArrayList<>(); // lista de campos inicializada y vacia
        archivoActual        = null;
        metadataActual       = null;
        rafActual            = null;
        haycambiosSinGuardar = false;
        
        // cambiandole los items de opciones de la combobox
        JComboBox_TipoDeDatoCampo.removeAllItems();
        JComboBox_TipoDeDatoCampo.addItem("int"); // 0 = int
        JComboBox_TipoDeDatoCampo.addItem("float"); // 1 = float
        JComboBox_TipoDeDatoCampo.addItem("boolean"); // 2 = bool
        JComboBox_TipoDeDatoCampo.addItem("char"); // 3 = char
        JComboBox_TipoDeDatoCampo.addItem("string"); // 4 =string
        
        archivoActual = null;  // inicial no hay archivo
        this.setTitle("Mini DBMS — Sin archivo abierto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDialog_CrearCampos = new javax.swing.JDialog();
        JPanel_CrearCampos = new javax.swing.JPanel();
        JLabel_CrearCampos = new javax.swing.JLabel();
        JLabel_NombreCampos = new javax.swing.JLabel();
        JTextField_NombreDelCampo = new javax.swing.JTextField();
        JLabel_TipoDeCampo = new javax.swing.JLabel();
        JLabel_LlavePrimSecun = new javax.swing.JLabel();
        JLabel_TamanioCampo = new javax.swing.JLabel();
        JTextField_TamanioCampo = new javax.swing.JTextField();
        JButton_CrearCampos = new javax.swing.JButton();
        JButton_SalirCrearCampos = new javax.swing.JButton();
        JRadioButton_LlavePrimaria = new javax.swing.JRadioButton();
        JRadioButton_LlaveSecundaria = new javax.swing.JRadioButton();
        JComboBox_TipoDeDatoCampo = new javax.swing.JComboBox<>();
        JDialog_ListarCampos = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        JLabel_CrearCampos1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_ListaDeCampos = new javax.swing.JTable();
        JButton_ModificarCampos = new javax.swing.JButton();
        JButton_BorrarCampos = new javax.swing.JButton();
        JButton_SalirListaCampos = new javax.swing.JButton();
        JPanel_JFrame = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JMenuBar_1 = new javax.swing.JMenuBar();
        JMenu_Archivo = new javax.swing.JMenu();
        JMenuItem_CrearArchivo = new javax.swing.JMenuItem();
        JMenuItem_AbrirArchivo = new javax.swing.JMenuItem();
        JMenuItem_GuardarCambios = new javax.swing.JMenuItem();
        JMenuItem_CerrarArchivo = new javax.swing.JMenuItem();
        JMenuItem_SalirProg = new javax.swing.JMenuItem();
        JMenu_Campos = new javax.swing.JMenu();
        JMenuItem_CrearCampos = new javax.swing.JMenuItem();
        JMenuItem_ListarCampos = new javax.swing.JMenuItem();
        JMenuItem_ModificarCampos = new javax.swing.JMenuItem();
        JMenuItem_BorrarCampos = new javax.swing.JMenuItem();
        JMenu_Registros = new javax.swing.JMenu();
        JMenuItem_IntroducirRegistros = new javax.swing.JMenuItem();
        JMenuItem_ModificarRegistros = new javax.swing.JMenuItem();
        JMenuItem_BuscarRegistros = new javax.swing.JMenuItem();
        JMenuItem_BorrarRegistros = new javax.swing.JMenuItem();
        JMenuItem_ListarRegistros = new javax.swing.JMenuItem();
        JMenuItem_CargarRegistrosPrueba = new javax.swing.JMenuItem();
        JMenuItem_CruzarArchivos = new javax.swing.JMenuItem();

        JPanel_CrearCampos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabel_CrearCampos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JLabel_CrearCampos.setText("Crear Campos");
        JPanel_CrearCampos.add(JLabel_CrearCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 24, -1, -1));

        JLabel_NombreCampos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLabel_NombreCampos.setText("Nombre del campo:");
        JPanel_CrearCampos.add(JLabel_NombreCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 109, 234, -1));
        JPanel_CrearCampos.add(JTextField_NombreDelCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 113, 280, -1));

        JLabel_TipoDeCampo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLabel_TipoDeCampo.setText("Tipo de dato del campo:");
        JPanel_CrearCampos.add(JLabel_TipoDeCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 154, 235, -1));

        JLabel_LlavePrimSecun.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLabel_LlavePrimSecun.setText("Llave primaria/Llave secundaria:");
        JLabel_LlavePrimSecun.setToolTipText("En caso no aplique a ninguna de las dos, no seleccionar");
        JPanel_CrearCampos.add(JLabel_LlavePrimSecun, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 241, -1, 34));

        JLabel_TamanioCampo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLabel_TamanioCampo.setText("Tamaño del campo:");
        JPanel_CrearCampos.add(JLabel_TamanioCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 198, 234, -1));
        JPanel_CrearCampos.add(JTextField_TamanioCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 201, 280, -1));

        JButton_CrearCampos.setText("Crear campo");
        JButton_CrearCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_CrearCamposMouseClicked(evt);
            }
        });
        JPanel_CrearCampos.add(JButton_CrearCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 357, -1, -1));

        JButton_SalirCrearCampos.setBackground(new java.awt.Color(204, 0, 0));
        JButton_SalirCrearCampos.setText("Salir");
        JButton_SalirCrearCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_SalirCrearCamposMouseClicked(evt);
            }
        });
        JPanel_CrearCampos.add(JButton_SalirCrearCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 357, -1, -1));

        JRadioButton_LlavePrimaria.setText("Llave primaria");
        JRadioButton_LlavePrimaria.setToolTipText("");
        JPanel_CrearCampos.add(JRadioButton_LlavePrimaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 293, 100, -1));

        JRadioButton_LlaveSecundaria.setText("Llave secundaria");
        JRadioButton_LlaveSecundaria.addActionListener(this::JRadioButton_LlaveSecundariaActionPerformed);
        JPanel_CrearCampos.add(JRadioButton_LlaveSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 293, 122, -1));

        JComboBox_TipoDeDatoCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JPanel_CrearCampos.add(JComboBox_TipoDeDatoCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 158, 280, -1));

        javax.swing.GroupLayout JDialog_CrearCamposLayout = new javax.swing.GroupLayout(JDialog_CrearCampos.getContentPane());
        JDialog_CrearCampos.getContentPane().setLayout(JDialog_CrearCamposLayout);
        JDialog_CrearCamposLayout.setHorizontalGroup(
            JDialog_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_CrearCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JDialog_CrearCamposLayout.setVerticalGroup(
            JDialog_CrearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_CrearCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JLabel_CrearCampos1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JLabel_CrearCampos1.setText("Lista de Campos");

        JTable_ListaDeCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTable_ListaDeCampos);

        JButton_ModificarCampos.setText("Modificar Campo");

        JButton_BorrarCampos.setText("Borrar Campos");

        JButton_SalirListaCampos.setBackground(new java.awt.Color(204, 0, 0));
        JButton_SalirListaCampos.setText("Salir");
        JButton_SalirListaCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButton_SalirListaCamposMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(JLabel_CrearCampos1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JButton_ModificarCampos)
                                .addGap(18, 18, 18)
                                .addComponent(JButton_BorrarCampos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JButton_SalirListaCampos))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(JLabel_CrearCampos1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton_ModificarCampos)
                    .addComponent(JButton_BorrarCampos)
                    .addComponent(JButton_SalirListaCampos))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JDialog_ListarCamposLayout = new javax.swing.GroupLayout(JDialog_ListarCampos.getContentPane());
        JDialog_ListarCampos.getContentPane().setLayout(JDialog_ListarCamposLayout);
        JDialog_ListarCamposLayout.setHorizontalGroup(
            JDialog_ListarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JDialog_ListarCamposLayout.setVerticalGroup(
            JDialog_ListarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMaritimo.jpg"))); // NOI18N

        javax.swing.GroupLayout JPanel_JFrameLayout = new javax.swing.GroupLayout(JPanel_JFrame);
        JPanel_JFrame.setLayout(JPanel_JFrameLayout);
        JPanel_JFrameLayout.setHorizontalGroup(
            JPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPanel_JFrameLayout.setVerticalGroup(
            JPanel_JFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JMenu_Archivo.setText("Archivos");
        JMenu_Archivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenu_ArchivoMouseClicked(evt);
            }
        });
        JMenu_Archivo.addActionListener(this::JMenu_ArchivoActionPerformed);

        JMenuItem_CrearArchivo.setText("Crear archivo");
        JMenuItem_CrearArchivo.addActionListener(this::JMenuItem_CrearArchivoActionPerformed);
        JMenu_Archivo.add(JMenuItem_CrearArchivo);

        JMenuItem_AbrirArchivo.setText("Abrir archivo");
        JMenuItem_AbrirArchivo.addActionListener(this::JMenuItem_AbrirArchivoActionPerformed);
        JMenu_Archivo.add(JMenuItem_AbrirArchivo);

        JMenuItem_GuardarCambios.setText("Guardar cambios");
        JMenuItem_GuardarCambios.addActionListener(this::JMenuItem_GuardarCambiosActionPerformed);
        JMenu_Archivo.add(JMenuItem_GuardarCambios);

        JMenuItem_CerrarArchivo.setText("Cerrar archivo");
        JMenuItem_CerrarArchivo.addActionListener(this::JMenuItem_CerrarArchivoActionPerformed);
        JMenu_Archivo.add(JMenuItem_CerrarArchivo);

        JMenuItem_SalirProg.setText("Salir");
        JMenuItem_SalirProg.addActionListener(this::JMenuItem_SalirProgActionPerformed);
        JMenu_Archivo.add(JMenuItem_SalirProg);

        JMenuBar_1.add(JMenu_Archivo);

        JMenu_Campos.setText("Campos");

        JMenuItem_CrearCampos.setText("Crear campos");
        JMenuItem_CrearCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenuItem_CrearCamposMouseClicked(evt);
            }
        });
        JMenuItem_CrearCampos.addActionListener(this::JMenuItem_CrearCamposActionPerformed);
        JMenu_Campos.add(JMenuItem_CrearCampos);

        JMenuItem_ListarCampos.setText("Listar campos");
        JMenuItem_ListarCampos.addActionListener(this::JMenuItem_ListarCamposActionPerformed);
        JMenu_Campos.add(JMenuItem_ListarCampos);

        JMenuItem_ModificarCampos.setText("Modificar campos");
        JMenu_Campos.add(JMenuItem_ModificarCampos);

        JMenuItem_BorrarCampos.setText("Borrar campos");
        JMenu_Campos.add(JMenuItem_BorrarCampos);

        JMenuBar_1.add(JMenu_Campos);

        JMenu_Registros.setText("Registros");

        JMenuItem_IntroducirRegistros.setText("Introducir registros");
        JMenu_Registros.add(JMenuItem_IntroducirRegistros);

        JMenuItem_ModificarRegistros.setText("Modificar registros");
        JMenu_Registros.add(JMenuItem_ModificarRegistros);

        JMenuItem_BuscarRegistros.setText("Buscar registros");
        JMenu_Registros.add(JMenuItem_BuscarRegistros);

        JMenuItem_BorrarRegistros.setText("Borrar registros");
        JMenu_Registros.add(JMenuItem_BorrarRegistros);

        JMenuItem_ListarRegistros.setText("Listar registros");
        JMenu_Registros.add(JMenuItem_ListarRegistros);

        JMenuItem_CargarRegistrosPrueba.setText("Cargar registros ");
        JMenu_Registros.add(JMenuItem_CargarRegistrosPrueba);

        JMenuItem_CruzarArchivos.setText("Cruzar archivos");
        JMenu_Registros.add(JMenuItem_CruzarArchivos);

        JMenuBar_1.add(JMenu_Registros);

        setJMenuBar(JMenuBar_1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_JFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_JFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenu_ArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenu_ArchivoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenu_ArchivoMouseClicked

    private void JMenuItem_CrearArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_CrearArchivoActionPerformed
        // Si hay un archivo abierto con cambios, preguntar antes de continuar
        if (!cerrarArchivoActual()) return;
 
        JFileChooser archi = new JFileChooser();
        archi.setDialogTitle("Crear nuevo archivo...");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de datos (*.dat)", "dat");
        archi.setFileFilter(filtro);
 
        if (archi.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(this, "No se seleccionó ningún archivo.");
            return;
        }
 
        // Asegurar extensión .dat
        String ruta = archi.getSelectedFile().getAbsolutePath();
        if (!ruta.toLowerCase().endsWith(".dat")) ruta += ".dat";
        File archivoFinal = new File(ruta);
 
        if (archivoFinal.exists()) {
            JOptionPane.showMessageDialog(this,
                "El archivo ya existe.\nUse 'Abrir archivo' para abrirlo.");
            return;
        }
 
        try {
            // Crear el archivo binario y escribir la metadata inicial (header vacío)
            rafActual = new RandomAccessFile(archivoFinal, "rw");
            metadataActual = new Metadata();
            String nombreSinExt = archivoFinal.getName().replace(".dat", "");
            metadataActual.inicializar(nombreSinExt, (byte) 0); // 0 = best fit
            metadataActual.escribirMetadata(rafActual);
 
            archivoActual = archivoFinal;
            lista_Campos.clear();
            haycambiosSinGuardar = false;
            actualizarTituloVentana();
 
            JOptionPane.showMessageDialog(this,
                "Archivo creado: " + archivoFinal.getName() +
                "\n\nAhora defina los campos desde el menú Campos.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                "Error al crear el archivo: " + e.getMessage());
            cerrarRecursos();
        }    
    }//GEN-LAST:event_JMenuItem_CrearArchivoActionPerformed

    private void JMenuItem_AbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_AbrirArchivoActionPerformed
        if (!cerrarArchivoActual()) return;
 
        JFileChooser archi = new JFileChooser();
        archi.setDialogTitle("Abrir archivo de datos...");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de datos (*.dat)", "dat");
        archi.setFileFilter(filter);
 
        if (archi.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(this, "No se seleccionó ningún archivo.");
            return;
        }
 
        File archivoSeleccionado = archi.getSelectedFile();
        if (!archivoSeleccionado.exists()) {
            JOptionPane.showMessageDialog(this, "El archivo no existe.");
            return;
        }
 
        try {
            rafActual = new RandomAccessFile(archivoSeleccionado, "rw");
            metadataActual = Metadata.leerMetadata(rafActual);
            archivoActual = archivoSeleccionado;
            haycambiosSinGuardar = false;
 
            // Reconstruir lista_Campos desde la metadata leída del disco
            sincronizarListaCampos();
            actualizarTituloVentana();
 
            JOptionPane.showMessageDialog(this,
                "Archivo abierto: " + archivoSeleccionado.getName() +
                "\nCampos: "           + metadataActual.getHeader().getCantidad_campos() +
                "\nRegistros activos: " + metadataActual.getHeader().getRegistros_actives());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                "Error al abrir el archivo: " + e.getMessage());
            cerrarRecursos();
        }    
    }//GEN-LAST:event_JMenuItem_AbrirArchivoActionPerformed

        
    // No funciono con Mouse Click - JDialogs
    private void JMenuItem_CrearCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenuItem_CrearCamposMouseClicked
        // vacio
    }//GEN-LAST:event_JMenuItem_CrearCamposMouseClicked

    // Abre el JDialog_CrearCampos y cerrando el JFrame
    private void JMenuItem_CrearCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_CrearCamposActionPerformed
        this.setVisible(false);
        expandir(JDialog_CrearCampos);
    }//GEN-LAST:event_JMenuItem_CrearCamposActionPerformed

    // Crear los campos una vez ya haya ingresado los datos requeridos
    private void JButton_CrearCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_CrearCamposMouseClicked
        Campos temporal = new Campos();
        
        // Verificar que los campos no esten vacios
        // 1. Verificando que el TextField del campo no este vacio 
        if (JTextField_NombreDelCampo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(JDialog_CrearCampos, "Ingrese el campo requerido (Nombre del campo)");
            return;
        }
        
        // 2. Guardar el nombre del campo en temporal con setNombre
        temporal.setNombre(JTextField_NombreDelCampo.getText());
        
        // 3. Verificar el ComboBox de que tipo de dato va ser el campo
        // Como es int private int tipoDato; entonces => 0 = int, 1 = float, 2 = bool, 3 = char, 4 = string
        int tipo_Seleccionado = JComboBox_TipoDeDatoCampo.getSelectedIndex(); // indice del seleccionado
        switch (tipo_Seleccionado){
            case 0 : // int
                temporal.setTipoDato(0);
                temporal.setTamanio("4");
                JTextField_TamanioCampo.setText("4");
                JTextField_TamanioCampo.setEnabled(false); // para que no pueda cambiar el "4" 
                break;
            case 1: // float
                temporal.setTipoDato(1);
                temporal.setTamanio("8");
                JTextField_TamanioCampo.setText("8");
                JTextField_TamanioCampo.setEnabled(false); // mismo pero "8"
                break;
            case 2: // bool
                temporal.setTipoDato(2);
                temporal.setTamanio("1"); // true/false solo ocupa 1 byte de espacio
                JTextField_TamanioCampo.setText("1");
                JTextField_TamanioCampo.setEnabled(false);
                break;
            case 3: // char
                if (JTextField_TamanioCampo.getText().isEmpty()) { // verificar que el tamanio no este vacio
                    JOptionPane.showMessageDialog(JDialog_CrearCampos, "Ingrese el campo requerido (tamanio del char)");
                    return;
                }
                temporal.setTipoDato(3);
                temporal.setTamanio(JTextField_TamanioCampo.getText());
                JTextField_TamanioCampo.setEnabled(true);
                break;
            case 4: // string
                if (JTextField_TamanioCampo.getText().isEmpty()) { // verificar que el tamanio no este vacio
                    JOptionPane.showMessageDialog(JDialog_CrearCampos, "Ingrese el campo requerido (tamanio del string)");
                    return;
                }
                temporal.setTipoDato(4);
                temporal.setTamanio(JTextField_TamanioCampo.getText());
                JTextField_TamanioCampo.setEnabled(true);
                break;
        }
        
        // 4. Llaves primarias y secundarias asignadas - validando que solo pueda escoger 1 pero no ambos y si no se escoge ambos dejando como campo normal
        if (JRadioButton_LlavePrimaria.isSelected()) {
            temporal.setLlavePrimaria(true);
            temporal.setLlaveSecundaria(false);
        } else if (JRadioButton_LlaveSecundaria.isSelected()) {
            temporal.setLlavePrimaria(false);
            temporal.setLlaveSecundaria(true);
        } else { // --> campo normal
            temporal.setLlavePrimaria(false);
            temporal.setLlaveSecundaria(false);
        }
        
        // 5. Agregarla a la lista_campos - temporal
        lista_Campos.add(temporal); // ya agregando el Campo temporal con todos lo requerido (nombre, tipodato, tamanio, llaveprimaria, llavesecundaria)
        
        // 6. mensaje que muestra que se realizo la creacion de campo
        JOptionPane.showMessageDialog(JDialog_CrearCampos, "Campo '" + temporal.getNombre() + "' ha creado");
        
        // 7. limpiar los componentes
        JTextField_NombreDelCampo.setText("");
        JTextField_TamanioCampo.setText("");
        
    }//GEN-LAST:event_JButton_CrearCamposMouseClicked

    private void JRadioButton_LlaveSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioButton_LlaveSecundariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRadioButton_LlaveSecundariaActionPerformed

    // Cerrar el JDialog de crear campos y mostrar el JFrame
    private void JButton_SalirCrearCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_SalirCrearCamposMouseClicked
        this.setVisible(true);
        JDialog_CrearCampos.dispose();
    }//GEN-LAST:event_JButton_SalirCrearCamposMouseClicked

    // Cerrar el JDialog de Listar campos y mostrar el JFrame
    private void JButton_SalirListaCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButton_SalirListaCamposMouseClicked
        this.setVisible(true);
        JDialog_ListarCampos.dispose();
    }//GEN-LAST:event_JButton_SalirListaCamposMouseClicked

    
    private void JMenu_ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenu_ArchivoActionPerformed
        
    }//GEN-LAST:event_JMenu_ArchivoActionPerformed

    // Salir del JFrame (salir del programa en corto
    private void JMenuItem_SalirProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_SalirProgActionPerformed
        if (cerrarArchivoActual()) {
            System.exit(0);
        }
    }//GEN-LAST:event_JMenuItem_SalirProgActionPerformed

    // Guardar los cambios hechos - archivo
    private void JMenuItem_GuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_GuardarCambiosActionPerformed
        if (!verificarArchivoAbierto()) return;
        guardarCambios();
    }//GEN-LAST:event_JMenuItem_GuardarCambiosActionPerformed

    // Cerrar el archivo 
    private void JMenuItem_CerrarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_CerrarArchivoActionPerformed
        if (!verificarArchivoAbierto()) return;
        if (cerrarArchivoActual()) {
            JOptionPane.showMessageDialog(this, "Archivo cerrado correctamente.");
        }
    }//GEN-LAST:event_JMenuItem_CerrarArchivoActionPerformed

    private void JMenuItem_ListarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_ListarCamposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuItem_ListarCamposActionPerformed

    // Verifica que haya un archivo abierto antes de cualquier operación
    private boolean verificarArchivoAbierto() {
        if (archivoActual == null || rafActual == null || metadataActual == null) {
            JOptionPane.showMessageDialog(this,
                "No hay ningún archivo abierto.\n" +
                "Use Archivos → Crear archivo  o  Archivos → Abrir archivo.");
            return false;
        }
        return true;
    }
 
    // Guarda la metadata completa en disco
    private boolean guardarCambios() {
        if (rafActual == null || metadataActual == null) return false;
        try {
            metadataActual.escribirMetadata(rafActual);
            haycambiosSinGuardar = false;
            actualizarTituloVentana();
            JOptionPane.showMessageDialog(this, "Cambios guardados correctamente.");
            return true;
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                "Error al guardar: " + e.getMessage());
            return false;
        }
    }
 
    // Pregunta si guardar, cierra el archivo. Retorna false si el usuario canceló.
    private boolean cerrarArchivoActual() {
        if (archivoActual == null) return true; // ya cerrado, OK
 
        if (haycambiosSinGuardar) {
            int resp = JOptionPane.showConfirmDialog(this,
                "Hay cambios sin guardar en '" + archivoActual.getName() + "'.\n" +
                "¿Desea guardarlos?",
                "Guardar cambios",
                JOptionPane.YES_NO_CANCEL_OPTION);
 
            if (resp == JOptionPane.YES_OPTION) {
                if (!guardarCambios()) return false;
            } else if (resp == JOptionPane.CANCEL_OPTION
                    || resp == JOptionPane.CLOSED_OPTION) {
                return false; // usuario canceló
            }
            // NO_OPTION: continuar sin guardar
        }
        cerrarRecursos();
        return true;
    }
 
    // Cierra el RandomAccessFile y limpia todas las variables de estado
    private void cerrarRecursos() {
        try {
            if (rafActual != null) rafActual.close();
        } catch (IOException ignored) {
        } finally {
            rafActual            = null;
            metadataActual       = null;
            archivoActual        = null;
            haycambiosSinGuardar = false;
            lista_Campos.clear();
            actualizarTituloVentana();
        }
    }
 
    // Al abrir un archivo existente: reconstruye lista_Campos desde la metadata
    private void sincronizarListaCampos() {
        lista_Campos.clear();
        DescriptorCampos[] tabla = metadataActual.getTablaCampos();
        if (tabla == null) return;
        for (DescriptorCampos dc : tabla) {
            lista_Campos.add(new Campos(
                dc.getNombre_campo(),
                dc.getTipo(),
                String.valueOf(dc.getTamanio_max()),
                dc.getLlave_primaria()   == 1,
                dc.getLlave_secundaria() == 1
            ));
        }
    }
 
    // Limpia el formulario del diálogo Crear Campos para una nueva entrada
    private void limpiarFormularioCampo() {
        JTextField_NombreDelCampo.setText("");
        JTextField_TamanioCampo.setText("");
        JTextField_TamanioCampo.setEnabled(true);
        JComboBox_TipoDeDatoCampo.setSelectedIndex(0);
        JRadioButton_LlavePrimaria.setSelected(false);
        JRadioButton_LlaveSecundaria.setSelected(false);
    }
 
    // Actualiza el título de la ventana con el nombre del archivo activo
    private void actualizarTituloVentana() {
        if (archivoActual != null) {
            String marca = haycambiosSinGuardar ? " *" : "";
            this.setTitle("Mini DBMS — " + archivoActual.getName() + marca);
        } else {
            this.setTitle("Mini DBMS — Sin archivo abierto");
        }
    }
 
    // Carga la JTable del diálogo Listar Campos con los campos actuales
    // Llama este método ANTES de abrir JDialog_ListarCampos
    private void cargarTablaCampos() {
        String[] tipos = {"int", "float", "boolean", "char", "string"};
        String[] columnas = {"#", "Nombre", "Tipo", "Tamaño", "L.Primaria", "L.Secundaria"};
 
        Object[][] datos = new Object[lista_Campos.size()][6];
        for (int i = 0; i < lista_Campos.size(); i++) {
            Campos c = lista_Campos.get(i);
            datos[i][0] = i + 1;
            datos[i][1] = c.getNombre();
            datos[i][2] = (c.getTipoDato() >= 0 && c.getTipoDato() < tipos.length)
                          ? tipos[c.getTipoDato()] : "?";
            datos[i][3] = c.getTamanio();
            datos[i][4] = c.isLlavePrimaria()  ? "Sí" : "No";
            datos[i][5] = c.isLlaveSecundaria() ? "Sí" : "No";
        }
 
        JTable_ListaDeCampos.setModel(
            new javax.swing.table.DefaultTableModel(datos, columnas) {
                @Override
                public boolean isCellEditable(int row, int col) { return false; }
            }
        );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }
    
    // para las JDialogs
    public void expandir(JDialog ventana) {
        ventana.pack();
        ventana.setModal(true);
        ventana.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_BorrarCampos;
    private javax.swing.JButton JButton_CrearCampos;
    private javax.swing.JButton JButton_ModificarCampos;
    private javax.swing.JButton JButton_SalirCrearCampos;
    private javax.swing.JButton JButton_SalirListaCampos;
    private javax.swing.JComboBox<String> JComboBox_TipoDeDatoCampo;
    private javax.swing.JDialog JDialog_CrearCampos;
    private javax.swing.JDialog JDialog_ListarCampos;
    private javax.swing.JLabel JLabel_CrearCampos;
    private javax.swing.JLabel JLabel_CrearCampos1;
    private javax.swing.JLabel JLabel_LlavePrimSecun;
    private javax.swing.JLabel JLabel_NombreCampos;
    private javax.swing.JLabel JLabel_TamanioCampo;
    private javax.swing.JLabel JLabel_TipoDeCampo;
    private javax.swing.JMenuBar JMenuBar_1;
    private javax.swing.JMenuItem JMenuItem_AbrirArchivo;
    private javax.swing.JMenuItem JMenuItem_BorrarCampos;
    private javax.swing.JMenuItem JMenuItem_BorrarRegistros;
    private javax.swing.JMenuItem JMenuItem_BuscarRegistros;
    private javax.swing.JMenuItem JMenuItem_CargarRegistrosPrueba;
    private javax.swing.JMenuItem JMenuItem_CerrarArchivo;
    private javax.swing.JMenuItem JMenuItem_CrearArchivo;
    private javax.swing.JMenuItem JMenuItem_CrearCampos;
    private javax.swing.JMenuItem JMenuItem_CruzarArchivos;
    private javax.swing.JMenuItem JMenuItem_GuardarCambios;
    private javax.swing.JMenuItem JMenuItem_IntroducirRegistros;
    private javax.swing.JMenuItem JMenuItem_ListarCampos;
    private javax.swing.JMenuItem JMenuItem_ListarRegistros;
    private javax.swing.JMenuItem JMenuItem_ModificarCampos;
    private javax.swing.JMenuItem JMenuItem_ModificarRegistros;
    private javax.swing.JMenuItem JMenuItem_SalirProg;
    private javax.swing.JMenu JMenu_Archivo;
    private javax.swing.JMenu JMenu_Campos;
    private javax.swing.JMenu JMenu_Registros;
    private javax.swing.JPanel JPanel_CrearCampos;
    private javax.swing.JPanel JPanel_JFrame;
    private javax.swing.JRadioButton JRadioButton_LlavePrimaria;
    private javax.swing.JRadioButton JRadioButton_LlaveSecundaria;
    private javax.swing.JTable JTable_ListaDeCampos;
    private javax.swing.JTextField JTextField_NombreDelCampo;
    private javax.swing.JTextField JTextField_TamanioCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private Metadata metadataActual;       // metadata activa del archivo
    private RandomAccessFile rafActual;    // conexión binaria al archivo
    private boolean haycambiosSinGuardar;  // bandera de cambios pendientes
}
